In [25]:
import pandas as pd

caract = pd.read_csv("../data/raw/caract-2024.csv", sep=";")
usagers = pd.read_csv("../data/raw/usagers-2024.csv", sep=";")
display(caract.head())
display(caract.shape)
display(caract.columns)

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000"
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"

(54402, 15)

Index(['Num_Acc', 'jour', 'mois', 'an', 'hrmn', 'lum', 'dep', 'com', 'agg',
       'int', 'atm', 'col', 'adr', 'lat', 'long'],
      dtype='str')

In [26]:
display(usagers.head())
display(usagers.shape)
display(usagers.columns)

,Num_Acc,id_usager,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202400000001,203 988 581,155 781 758,A01,1,1,3,1,2003.0,2,1,-1,-1,-1,-1,-1
1,202400000001,203 988 582,155 781 759,B01,1,1,1,1,1997.0,4,1,-1,-1,-1,-1,-1
2,202400000002,203 988 579,155 781 757,A01,10,3,3,2,1927.0,5,0,-1,-1,3,3,1
3,202400000002,203 988 580,155 781 757,A01,1,1,1,1,1987.0,4,1,0,-1,3,3,1
4,202400000003,203 988 574,155 781 756,A01,2,2,4,2,2007.0,5,8,0,-1,-1,-1,-1

(125187, 16)

Index(['Num_Acc', 'id_usager', 'id_vehicule', 'num_veh', 'place', 'catu',
       'grav', 'sexe', 'an_nais', 'trajet', 'secu1', 'secu2', 'secu3', 'locp',
       'actp', 'etatp'],
      dtype='str')

In [27]:
caract.info()

<class 'pandas.DataFrame'>
RangeIndex: 54402 entries, 0 to 54401
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  54402 non-null  int64
 1   jour     54402 non-null  int64
 2   mois     54402 non-null  int64
 3   an       54402 non-null  int64
 4   hrmn     54402 non-null  str
 5   lum      54402 non-null  int64
 6   dep      54402 non-null  str
 7   com      54402 non-null  str
 8   agg      54402 non-null  int64
 9   int      54402 non-null  int64
 10  atm      54402 non-null  int64
 11  col      54402 non-null  int64
 12  adr      52092 non-null  str
 13  lat      54402 non-null  str
 14  long     54402 non-null  str
dtypes: int64(9), str(6)
memory usage: 6.2 MB

In [28]:
caract["lum"].value_counts()

lum
1    35580
5     8499
3     6101
2     3599
4      623
Name: count, dtype: int64

In [29]:
usagers["grav"].value_counts()

grav
1    52920
4    49709
3    19126
2     3432
Name: count, dtype: int64

In [30]:
display(caract["Num_Acc"].nunique())
display(usagers["Num_Acc"].nunique())

54402

54402

In [85]:
display(caract["lum"].isin([3, 4, 5]).mean())

tues = usagers[usagers["grav"] == 2]
nb_pietons_tues = (tues["catu"] == 3).sum()
part_pietons = (tues["catu"] == 3).mean()
print(nb_pietons_tues)
print(f"{part_pietons:.1%}")

np.float64(0.2798242711665012)

498
14.5%

In [86]:
for col in usagers.columns:
    nb = (usagers[col] == -1).sum()
    print(col, nb)

Num_Acc 0
id_usager 0
id_vehicule 0
num_veh 0
place 3
catu 0
grav 0
sexe 2395
an_nais 0
trajet 2626
secu1 2103
secu2 53813
secu3 113133
locp 61771
actp 0
etatp 114932